-- ====================================================
-- VAPE STREET BD - SAFE SUPABASE INITIALIZATION SCHEMA
-- ====================================================

-- 1. Create Products Table
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  price NUMERIC NOT NULL,
  original_price NUMERIC NULL,
  description TEXT,
  image TEXT NOT NULL,
  images JSONB NULL,
  specs JSONB NULL,
  badge TEXT NULL,
  rating NUMERIC DEFAULT 4.8
);

-- Enable RLS (Row Level Security)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Drop Policies if already exist to prevent "policy already exists" errors
DROP POLICY IF EXISTS "Allow public read access to products" ON public.products;
DROP POLICY IF EXISTS "Allow public insert to products" ON public.products;
DROP POLICY IF EXISTS "Allow public update to products" ON public.products;
DROP POLICY IF EXISTS "Allow public delete to products" ON public.products;

-- Create Policies for Public Access
CREATE POLICY "Allow public read access to products" 
  ON public.products FOR SELECT USING (true);

CREATE POLICY "Allow public insert to products" 
  ON public.products FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public update to products" 
  ON public.products FOR UPDATE USING (true);

CREATE POLICY "Allow public delete to products" 
  ON public.products FOR DELETE USING (true);

-- 2. Create Site Content Table
CREATE TABLE IF NOT EXISTS public.site_content (
  id TEXT PRIMARY KEY,
  content JSONB NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.site_content ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access to site_content" ON public.site_content;
DROP POLICY IF EXISTS "Allow public upsert to site_content" ON public.site_content;

CREATE POLICY "Allow public read access to site_content" 
  ON public.site_content FOR SELECT USING (true);

CREATE POLICY "Allow public upsert to site_content" 
  ON public.site_content FOR ALL USING (true) WITH CHECK (true);

-- 3. Create Storage Bucket for Product Images
INSERT INTO storage.buckets (id, name, public) 
VALUES ('product-images', 'product-images', true)
ON CONFLICT (id) DO NOTHING;

-- Drop Storage Policies if already exist
DROP POLICY IF EXISTS "Public Read Access for Product Images" ON storage.objects;
DROP POLICY IF EXISTS "Public Upload Access for Product Images" ON storage.objects;
DROP POLICY IF EXISTS "Public Update Access for Product Images" ON storage.objects;
DROP POLICY IF EXISTS "Public Delete Access for Product Images" ON storage.objects;

-- Create Storage Policies for Public Read & Upload Access
CREATE POLICY "Public Read Access for Product Images"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'product-images');

CREATE POLICY "Public Upload Access for Product Images"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'product-images');

CREATE POLICY "Public Update Access for Product Images"
  ON storage.objects FOR UPDATE
  USING (bucket_id = 'product-images');

CREATE POLICY "Public Delete Access for Product Images"
  ON storage.objects FOR DELETE
  USING (bucket_id = 'product-images');
